### ISSUE TITLE
ERROR VideoUnavailable  A lot of links are unavailable

### ISSUE THREAD

**Issue by Aanonymity3930** [coin-dataset/annotations#1]
HI, Thank you for your contribution!
There are actually many videos unavailable since some video may be deleted by the author.  Actually, I only downloaded 10927 videos. So we could not download them all, right?

**Comment by AndyTang15** [comment]
Hi, we are preparing one copy of the COIN dataset, you can email tys15@mails.tsinghua.edu.cn to obtain the it.

**Comment by yzheng97** [comment]
We have recently prepared another copy of the COIN dataset on Tsinghua cloud drive. Anyone who is interested can email [yu-zheng@tsinghua.edu.cn](mailto:yu-zheng@tsinghua.edu.cn) to obtain it.
